kind: Deployment
apiVersion: apps/v1
metadata:
  name: webfe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webfe
  template:
    metadata:
      labels:
        app: webfe
    spec:
      containers:
        - name: webfe
          image: docker.io/fazarrahman/webfe:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BE_HOST
              value: "http://192.168.64.3:32016"
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
    kind: Service
    apiVersion: v1
    metadata:
      name: webfe
    spec:
      type: NodePort
      ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
      selector:
        app: webfe